# Generated by Django 4.2 on 2024-11-07 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_savedpost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_actor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
